CREATE TABLE IF NOT EXISTS `sliders` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `media_type` ENUM('video','image') NOT NULL DEFAULT 'image',
  `media_file` VARCHAR(255) DEFAULT NULL,
  `overlay_opacity` INT NOT NULL DEFAULT 40,
  `display_order` INT NOT NULL DEFAULT 1,
  `heading` VARCHAR(500) DEFAULT NULL,
  `subheading` VARCHAR(500) DEFAULT NULL,
  `button_text` VARCHAR(100) DEFAULT NULL,
  `button_link` VARCHAR(255) DEFAULT NULL,
  `is_active` TINYINT(1) NOT NULL DEFAULT 1,
  `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
